mappings:
  SharethisTest: SunnySideUp\ShareThis\tests\SharethisTest
  FacebookFeed_UpdateTask: SunnySideUp\ShareThis\code\tasks\FacebookFeed_UpdateTask
  ShareThisSiteConfigDE: SunnySideUp\ShareThis\code\extension\ShareThisSiteConfigDE
  SocialNetworksSTE: SunnySideUp\ShareThis\code\extension\SocialNetworksSTE
  ShareThisSTE: SunnySideUp\ShareThis\code\extension\ShareThisSTE
  SocialNetworkingModelAdmin: SunnySideUp\ShareThis\code\cms\SocialNetworkingModelAdmin
  FacebookFeed_Page: SunnySideUp\ShareThis\code\model\FacebookFeed_Page
  ShareThisDataObject: SunnySideUp\ShareThis\code\model\ShareThisDataObject
  MyTwitterData: SunnySideUp\ShareThis\code\model\MyTwitterData
  FacebookFeed_Item: SunnySideUp\ShareThis\code\model\FacebookFeed_Item
  SocialNetworkingLinksDataObject: SunnySideUp\ShareThis\code\model\SocialNetworkingLinksDataObject
  MyTwitter: SunnySideUp\ShareThis\code\api\MyTwitter
  simple_html_dom_node: SunnySideUp\ShareThis\code\api\thirdparty\simple_html_dom_node
  simple_html_dom: SunnySideUp\ShareThis\code\api\thirdparty\simple_html_dom
  SilverstripeFacebookConnector: SunnySideUp\ShareThis\code\api\SilverstripeFacebookConnector
  ShareThisOptions: SunnySideUp\ShareThis\code\data\ShareThisOptions
  RemoveFacebookItemController: SunnySideUp\ShareThis\code\control\RemoveFacebookItemController
  Services_JSON: SunnySideUp\ShareThis\third_party\jsonwrapper\JSON\Services_JSON
  Services_JSON_Error: SunnySideUp\ShareThis\third_party\jsonwrapper\JSON\Services_JSON_Error
  TwitterOAuth: SunnySideUp\ShareThis\third_party\twitter_oauth\TwitterOAuth
  OAuthException: SunnySideUp\ShareThis\third_party\twitter_oauth\OAuthException
  OAuthConsumer: SunnySideUp\ShareThis\third_party\twitter_oauth\OAuthConsumer
  OAuthToken: SunnySideUp\ShareThis\third_party\twitter_oauth\OAuthToken
  OAuthSignatureMethod: SunnySideUp\ShareThis\third_party\twitter_oauth\OAuthSignatureMethod
  OAuthSignatureMethod_HMAC_SHA1: SunnySideUp\ShareThis\third_party\twitter_oauth\OAuthSignatureMethod_HMAC_SHA1
  OAuthSignatureMethod_PLAINTEXT: SunnySideUp\ShareThis\third_party\twitter_oauth\OAuthSignatureMethod_PLAINTEXT
  OAuthSignatureMethod_RSA_SHA1: SunnySideUp\ShareThis\third_party\twitter_oauth\OAuthSignatureMethod_RSA_SHA1
  OAuthRequest: SunnySideUp\ShareThis\third_party\twitter_oauth\OAuthRequest
  OAuthServer: SunnySideUp\ShareThis\third_party\twitter_oauth\OAuthServer
  OAuthDataStore: SunnySideUp\ShareThis\third_party\twitter_oauth\OAuthDataStore
  OAuthUtil: SunnySideUp\ShareThis\third_party\twitter_oauth\OAuthUtil
