---
Name: sharethis
Before: 'mysite/*'
After: 'framework/*','cms/*'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SunnySideUp\ShareThis\code\extension\ShareThisSiteConfigDE
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SunnySideUp\ShareThis\code\extension\ShareThisSTE
    - SunnySideUp\ShareThis\code\extension\SocialNetworksSTE
---
Only:
  classexists: DataObjectSorterDOD
---
SunnySideUp\ShareThis\code\model\ShareThisDataObject:
  extensions:
    - DataObjectSorterDOD
SunnySideUp\ShareThis\code\model\SocialNetworkingLinksDataObject:
  extensions:
    - DataObjectSorterDOD
