---
Name: sharethis
Before: 'mysite/*'
After: 'framework/*'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SunnySideUp\ShareThis\ShareThisSiteConfigDE

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SunnySideUp\ShareThis\ShareThisSTE
    - SunnySideUp\ShareThis\SocialNetworksSTE
---
Only:
  classexists: DataObjectSorterDOD
---
SunnySideUp\ShareThis\ShareThisDataObject:
  extensions:
    - DataObjectSorterDOD

SunnySideUp\ShareThis\SocialNetworkingLinksDataObject:
  extensions:
    - DataObjectSorterDOD
