---
Name: sharethis
Before: 'mysite/*'
After: 'framework/*','cms/*'
---

SiteConfig:
  extensions:
    - ShareThisSiteConfigDE

SiteTree:
  extensions:
    - ShareThisSTE
    - SocialNetworksSTE

---
Only:
  classexists: DataObjectSorterDOD
---

ShareThisDataObject:
  extensions:
    - DataObjectSorterDOD

SocialNetworkingLinksDataObject:
  extensions:
    - DataObjectSorterDOD


