---
Name: sharethis_routes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    removefacebooklink//$Action/$ID: SunnySideUp\ShareThis\code\control\RemoveFacebookItemController
